version: '3'
services:
    backend:
        container_name: backend
        build:
            context: ./Backend
            dockerfile: $PWD/Docker/Dockerfile.backend
        image:
            newshub-backend:latest
        ports:
            - "8080:8080"
    frontend:
        container_name: frontend
        build:
            context: ./Frontend
            dockerfile: $PWD/Docker/Dockerfile.frontend
        image:
            newshub-frontend:latest
        ports:
            - "80:4200"