version: '3'
services:
    backend:
        build:
            context: ./Backend
            dockerfile: $PWD/Docker/Dockerfile.backend
        image:
            newshub-backend:latest
        ports:
            - "8080:8080"